const GENERAL_SESSION_CHANGE = 'GENERAL_SESSION_CHANGE';
const LOGIN_SESSION_CHANGE = 'LOGIN_SESSION_CHANGE';
const PROFILE_SESSION_CHANGE = 'PROFILE_SESSION_CHANGE';

export {GENERAL_SESSION_CHANGE, LOGIN_SESSION_CHANGE, PROFILE_SESSION_CHANGE}